<?php include "head.phtml"; ?>

<div data-role="dialog" id="code-settings" data-to-top="true" data-on-show="$(this).addClass('open')" data-on-close="$(this).removeClass('open')">
    <div class="dialog-title">Code settings</div>
    <div class="dialog-content">

        <ul data-role="tabs" data-expand="true" class="flex-justify-center flex-justify-start-lg" id="settings-tabs">
            <li><a href="#code-settings-html">HTML</a></li>
            <li><a href="#code-settings-css">CSS</a></li>
            <li><a href="#code-settings-js">JS</a></li>
            <li><a href="#code-settings-details">Details</a></li>
        </ul>

        <div class="mt-4">
            <div id="code-settings-html">
                <div class="form-group">
                    <label class="text-medium reduce-1">HTML processor</label>
                    <select id="html_processor" name="html_processor" data-role="select"data-filter="false">
                        <option value="none">None</option>
                    </select>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add classes to &lt;html&gt;</label>
                    <input type="text" id="html_classes" name="html_classes" data-role="input" value="<?php echo $code['html_classes']?>">
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add classes to &lt;body&gt;</label>
                    <input type="text" id="body_classes" name="body_classes" data-role="input" value="<?php echo $code['body_classes']?>">
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Staff for &lt;head&gt;</label>
                    <textarea id="html_head" name="html_head" data-role="textarea" placeholder="<meta>, <link>, <script>"><?php echo $code['html_head']?></textarea>

                    <label class="text-medium reduce-1">Add tags: </label>

                    <button class="button mini" onclick="Sandbox.addMetaTag('viewport')">viewport</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:init')">metro4:init</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:locale')">metro4:locale</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:week_start')">metro4:week_start</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:cloak')">metro4:cloak</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:cloak_duration')">metro4:cloak_duration</button>
                </div>
            </div>

            <div id="code-settings-css">
                <div class="form-group">
                    <label class="text-medium reduce-1 d-block">CSS Base</label>
                    <input type="radio" data-role="radio" data-style="2" data-caption="Reset" name="css_base" value="reset" <?php echo $code['css_base'] === 'reset' ? 'checked' : '' ?>>
                    <input type="radio" data-role="radio" data-style="2" data-caption="Normalize" name="css_base" value="normalize" <?php echo $code['css_base'] === 'normalize' ? 'checked' : '' ?>>
                    <input type="radio" data-role="radio" data-style="2" data-caption="None" name="css_base" value="none" <?php echo $code['css_base'] === 'none' ? 'checked' : '' ?>>
                </div>

                <div class="form-group">
                    <label class="text-medium reduce-1">CSS processor</label>
                    <select id="css_processor" name="css_processor" data-role="select" data-filter="false">
                        <option value="none">None</option>
                    </select>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add external stylesheets</label>
                    <textarea id="css_external" name="css_external" data-role="textarea" placeholder="https://yourwebsite.com/style.css"><?php echo $code['css_external']?></textarea>
                    <span class="text-small text-muted">One file on one row</span>
                </div>
            </div>

            <div id="code-settings-js">
                <div class="form-group">
                    <label class="text-medium reduce-1">JS processor</label>
                    <select id="js_processor" name="js_processor" data-role="select" data-filter="false">
                        <option value="none">None</option>
                    </select>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add external javascript</label>
                    <textarea id="js_external" name="js_external" data-role="textarea" placeholder="https://yourwebsite.com/javascript.js"><?php echo $code['js_external']?></textarea>
                    <span class="text-small text-muted">One file on one row</span>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">User script type</label>
                    <input type="text" id="js_type" name="js_type" data-role="input" value="<?php echo $code['js_type']?>">
                </div>
            </div>

            <div id="code-settings-details">
                <div class="form-group">
                    <label class="text-medium reduce-1">Code description</label>
                    <textarea id="desc" name="desc" data-role="textarea"><?php echo $code['desc']?></textarea>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Code tags</label>
                    <input type="text" id="tags" name="tags" data-role="taginput" data-max-tags="5" value="<?php echo $code['tags']?>">
                    <span class="text-small text-muted">Input comma separated tags for your code. Maximum 5 tags.</span>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">This is template</label>
                    <div>
                        <input type="checkbox" id="code_type" name="code_type" value="code" data-role="switch" disabled data-caption="Yes">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="dialog-actions">
        <button type="button" class="button success js-dialog-close" onclick="Sandbox.saveCode(true)">Save</button>
        <button type="button" class="button link js-dialog-close">Cancel</button>
    </div>
</div>

<div class="container-fluid pos-fixed fixed-top z-fixed bg-light border-bottom bd-default pl-0 pr-0">
    <header class="app-bar pos-relative" data-role="appbar" data-expand-point="md">
        <a class="app-bar-item no-hover pr-0" href="/"><span class="mif-arrow-left mif-2x"></span></a>
        <a class="app-bar-item no-hover pr-0" href="/"><img src="<?php echo VIEW_PATH?>images/<?php echo $code['template_data']['icon']?>" title="<?php echo $code['template_data']['title']?>" style="height: 24px"></a>
        <div class="app-bar-container" id="code-title-label">
            <span class="brand text-bold enlarge-2 no-hover" id="code_title_label"><?php echo $code['title'] ?></span>
            <button class="button square" onclick="Sandbox.openTitleEditor()"><span class="mif-pencil"></span></button>
        </div>
        <div class="app-bar-container" id="code-title-editor" style="display: none">
            <input type="text" data-role="input" value="<?php echo $code['title'] ?>" id="code_title">
            <button class="button square success" onclick="Sandbox.saveTitle()"><span class="mif-floppy-disk"></span></button>
        </div>

        <ul class="app-bar-menu ml-auto">

            <?php if ($_SESSION['current'] != -1) {?>
            <li class="d-none d-block-md no-hover mr-1">
                <div class="dropdown-button">
                    <button class="button info marker-light dropdown-toggle"><span class="mif-add"></span></button>
                    <ul class="d-menu" data-role="dropdown">
                        <?php if (isset($top_templates) && count($top_templates) > 0) foreach ($top_templates as $template){?>
                            <li><a href="/code?template=<?php echo $template['name']?>"><img class="icon" src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>"><?php echo $template['title']?></a></li>
                        <?php }?>
                        <li class="divider"></li>
                        <?php if (isset($templates) && count($templates) > 0) foreach ($templates as $template){?>
                            <li><a href="/code?template=<?php echo $template['name']?>"><img class="icon" src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>"><?php echo $template['title']?></a></li>
                        <?php }?>
                    </ul>
                </div>
            </li>

            <li class="d-none-md">
                <a href="" class="dropdown-toggle">New</a>
                <ul class="d-menu" data-role="dropdown">
                    <?php if (isset($top_templates) && count($top_templates) > 0) foreach ($top_templates as $template){?>
                        <li><a href="/code?template=<?php echo $template['name']?>"><img class="icon" src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>"><?php echo $template['title']?></a></li>
                    <?php }?>
                    <li class="divider"></li>
                    <?php if (isset($templates) && count($templates) > 0) foreach ($templates as $template){?>
                        <li><a href="/code?template=<?php echo $template['name']?>"><img class="icon" src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>"><?php echo $template['title']?></a></li>
                    <?php }?>
                </ul>
            </li>
            <?php }?>

            <?php if ($_SESSION['current'] != -1 && $code['alien'] != 1) {?>
            <li title="Save code" class="d-none d-block-md no-hover"><a class="p-0" href="#" onclick="Sandbox.saveCode(true)"><button class="button square success"><span class="mif-floppy-disk icon"></span></button></a></li>
            <li class="d-none-md"><a href="#" onclick="Sandbox.saveCode(true)"><span>Save code</span></a></li>
            <?php }?>

            <li title="Debug code" class="d-none d-block-md no-hover" style="display: <?php echo $code['hash'] == 'new' ? 'none!important' : 'block'?>"><a class="p-0" target="_blank" id="code_page-debug_button" href="<?php echo $code['hash'] == 'new' ? '#' : '/'.$code['user_name'].'/debug/' . $code['hash'] ?>"><button class="button square alert"><span class="mif-bug icon"></span></button></a></li>
            <li class="d-none-md" style="display: <?php echo $code['hash'] == 'new' ? 'none' : 'block'?>"><a target="_blank" id="code_page-debug_button" href="<?php echo $code['hash'] == 'new' ? '#' : '/'.$code['user_name'].'/debug/' . $code['hash'] ?>"><span>Debug code</span></a></li>

            <?php if ($_SESSION['current'] != -1) {?>
            <li title="Fork code" class="d-none d-block-md no-hover" style="display: <?php echo $code['hash'] == 'new' ? 'none!important' : 'block'?>"><a class="p-0" id="code_page-fork_button" href="#" onclick="Sandbox.fork('<?php echo $code['hash']?>'); return false;"><button class="button square secondary"><span class="mif-copy icon"></span></button></a></li>
            <li class="d-none-md" style="display: <?php echo $code['hash'] == 'new' ? 'none' : 'block'?>"><a id="code_page-fork_button" href="#" onclick="Sandbox.fork('<?php echo $code['hash']?>'); return false;"><span>Fork code</span></a></li>
            <?php }?>

            <?php if ($_SESSION['current'] != -1) {?>
            <li title="Page layout" class="ml-1 d-none d-block-md no-hover">
                <div class="dropdown-button">
                    <button class="button p-0 warning" style="width: 40px;"><span class="mif-layers icon mif-2x"></span></button>
                    <ul id="layout-menu" class="t-menu compact vertical pos-absolute shadow-1 place-right" data-role="dropdown" style="top: 100%;">
                        <li class="<?php echo $_SESSION['layout'] === 'left' ? 'active' : ''?>" title="Left"><a href="#" onclick="Sandbox.layout('left', '<?php echo $code['hash']?>')"><img src="/Views/images/layout-left.png" class="icon"></a></li>
                        <li class="<?php echo $_SESSION['layout'] === 'right' ? 'active' : ''?>" title="Right"><a href="#" onclick="Sandbox.layout('right', '<?php echo $code['hash']?>')"><img src="/Views/images/layout-right.png" class="icon"></a></li>
                        <li class="<?php echo $_SESSION['layout'] === 'top' ? 'active' : ''?>" title="Top"><a href="#" onclick="Sandbox.layout('top', '<?php echo $code['hash']?>')"><img src="/Views/images/layout-top.png" class="icon"></a></li>
                        <li class="<?php echo $_SESSION['layout'] === 'bottom' ? 'active' : ''?>" title="Bottom"><a href="#" onclick="Sandbox.layout('bottom', '<?php echo $code['hash']?>')"><img src="/Views/images/layout-bottom.png" class="icon"></a></li>
                    </ul>
                </div>
            </li>
            <li class="d-none-md">
                <a class="dropdown-toggle">Layout</a>
                <ul class="d-menu place-right" data-role="dropdown">
                    <li><a href="#" onclick="Sandbox.layout('left', '<?php echo $code['hash']?>')">Layout left</a></li>
                    <li><a href="#" onclick="Sandbox.layout('right', '<?php echo $code['hash']?>')">Layout right</a></li>
                    <li><a href="#" onclick="Sandbox.layout('top', '<?php echo $code['hash']?>')">Layout top</a></li>
                    <li><a href="#" onclick="Sandbox.layout('bottom', '<?php echo $code['hash']?>')">Layout bottom</a></li>
                </ul>
            </li>
            <?php }?>

            <li title="Code settings" class="d-none d-block-md no-hover"><a class="p-0" href="#" onclick="Sandbox.openSettingsTab(1, this)"><button class="button square dark"><span class="mif-cogs icon"></span></button></a></li>
            <li class="d-none-md"><a href="#" onclick="Sandbox.openSettingsTab(1, this)"><span>Code settings</span></a></li>

            <?php if ($_SESSION['current'] != -1) {?>
            <li title="User options" class="ml-1 d-none d-block-md no-hover">
                <div class="dropdown-button">
                    <button class="button p-0" style="width: 40px;"><img class="h-100 va-baseline" data-role="gravatar" data-default="mm" data-email="<?php echo $_SESSION['user']['email']?>"></button>
                    <ul class="t-menu compact vertical pos-absolute shadow-1" data-role="dropdown" style="top: 100%;">
                        <li><a href="/"><span class="mif-dashboard"></span></a></li>
                        <li><a href="/profile"><span class="mif-cogs"></span></a></li>
                    </ul>
                </div>
            </li>

            <li class="d-none-md">
                <a class="dropdown-toggle"><?php echo $_SESSION['user']['name']?></a>
                <ul class="d-menu place-right" data-role="dropdown">
                    <li><a href="/">Dashboard</a></li>
                    <li><a href="/profile">Profile</a></li>
                </ul>
            </li>

            <li title="Logout" class="ml-1 mr-1 d-none d-block-md no-hover"><a class="p-0" href="/logout"><button class="button square"><span class="mif-exit icon"></span></button></a></li>
            <li class="d-none-md"><a href="/logout"></span><span>Logout</span></a></li>

            <?php } else {?>
                <li><a href="/login">Log in</a></li>
            <?php } ?>
        </ul>

    </header>
</div>

<form action="javascript:" id="editor_form" class="h-100">
    <input type="hidden" name="code_id" id="code_id" value="<?php echo $code['id'] ?>">
    <input type="hidden" name="code_hash" id="code_hash" value="<?php echo $code['hash'] ?>">
    <input type="hidden" name="template" id="template" value="<?php echo $code['template'] ?>">
    <input type="hidden" name="temp_file" id="temp_file" value="<?php echo $code['temp_file'] ?>">
    <input type="hidden" name="saved" id="saved" value="<?php echo $code['saved'] ?>">
    <input type="hidden" name="alien" id="alien" value="<?php echo $code['alien'] ?>">

    <div id="mobile-layout" class="d-none-lg">
        <?php include "mobile-layout.phtml"?>
    </div>

    <div id="wide-layout" class="d-none d-block-lg h-100">
        <?php include "layout-".$_SESSION['layout'].".phtml"?>
    </div>

</form>

<?php include "foot.phtml"; ?>
