<?php include "head.phtml"; ?>

<div data-role="dialog" id="code-settings" data-to-top="true" data-on-show="$(this).addClass('open')" data-on-close="$(this).removeClass('open')">
    <div class="dialog-title">Code settings</div>
    <div class="dialog-content">

        <ul data-role="tabs" data-expand="true">
            <li><a href="#code-settings-html">HTML</a></li>
            <li><a href="#code-settings-css">CSS</a></li>
            <li><a href="#code-settings-js">JavaScript</a></li>
            <li><a href="#code-settings-details">Details</a></li>
        </ul>

        <div class="mt-4">
            <div id="code-settings-html">
                <div class="form-group">
                    <label class="text-medium reduce-1">HTML processor</label>
                    <select id="html_processor" name="html_processor" data-role="select"data-filter="false">
                        <option value="none">None</option>
                    </select>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add classes to &lt;html&gt;</label>
                    <input type="text" id="html_classes" name="html_classes" data-role="input" value="<?php echo $code['html_classes']?>">
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add classes to &lt;body&gt;</label>
                    <input type="text" id="body_classes" name="body_classes" data-role="input" value="<?php echo $code['body_classes']?>">
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Staff for &lt;head&gt;</label>
                    <textarea id="html_head" name="html_head" data-role="textarea" placeholder="<meta>, <link>, <script>"><?php echo $code['html_head']?></textarea>

                    <label class="text-medium reduce-1">Add tags: </label>

                    <button class="button mini" onclick="Sandbox.addMetaTag('viewport')">viewport</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:init')">metro4:init</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:locale')">metro4:locale</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:week_start')">metro4:week_start</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:cloak')">metro4:cloak</button>
                    <button class="button mini" onclick="Sandbox.addMetaTag('metro4:cloak_duration')">metro4:cloak_duration</button>
                </div>
            </div>

            <div id="code-settings-css">
                <div class="form-group">
                    <label class="text-medium reduce-1">CSS processor</label>
                    <select id="css_processor" name="css_processor" data-role="select" data-filter="false">
                        <option value="none">None</option>
                    </select>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add external stylesheets</label>
                    <textarea id="css_external" name="css_external" data-role="textarea" placeholder="https://yourwebsite.com/style.css"></textarea>
                </div>
            </div>

            <div id="code-settings-js">
                <div class="form-group">
                    <label class="text-medium reduce-1">JS processor</label>
                    <select id="js_processor" name="js_processor" data-role="select" data-filter="false">
                        <option value="none">None</option>
                    </select>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Add external javascript</label>
                    <textarea id="js_external" name="js_external" data-role="textarea" placeholder="https://yourwebsite.com/javascript.js"></textarea>
                </div>
            </div>
            <div id="code-settings-details">
                <div class="form-group">
                    <label class="text-medium reduce-1">Code description</label>
                    <textarea id="desc" name="desc" data-role="textarea"><?php echo $code['desc']?></textarea>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">Code tags</label>
                    <input type="text" id="tags" name="tags" data-role="taginput" data-max-tags="5" value="<?php echo $code['tags']?>">
                    <span class="text-small text-muted">Input comma separated tags for your code. Maximum 5 tags.</span>
                </div>

                <div class="form-group mt-2">
                    <label class="text-medium reduce-1">This is template</label>
                    <div>
                        <input type="checkbox" id="code_type" name="code_type" value="code" data-role="switch" disabled data-caption="Yes">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="dialog-actions">
        <button type="button" class="button success js-dialog-close" onclick="Sandbox.saveCode(true)">Save</button>
        <button type="button" class="button link js-dialog-close">Cancel</button>
    </div>
</div>

<div class="container-fluid pos-fixed fixed-top z-fixed bg-light border-bottom bd-default pl-0 pr-0">
    <header class="app-bar pos-relative" data-role="appbar" data-expand-point="md">
        <a class="app-bar-item no-hover pr-0" href="/"><img src="<?php echo VIEW_PATH?>images/<?php echo $code['template_icon']?>" title="<?php echo $code['template_title']?>" style="height: 24px"></a>
        <div class="app-bar-container" id="code-title-label">
            <span class="brand text-bold enlarge-2 no-hover" id="code_title_label"><?php echo $code['title'] ?></span>
            <button class="button square" onclick="Sandbox.openTitleEditor()"><span class="mif-pencil"></span></button>
        </div>
        <div class="app-bar-container" id="code-title-editor" style="display: none">
            <input type="text" data-role="input" value="<?php echo $code['title'] ?>" id="code_title">
            <button class="button square success" onclick="Sandbox.saveTitle()"><span class="mif-floppy-disk"></span></button>
        </div>

        <ul class="app-bar-menu ml-auto">
            <li class="d-none d-block-md no-hover mr-1">
                <div class="dropdown-button">
                    <button class="button info marker-light dropdown-toggle"><span class="mif-add"></span></button>
                    <ul class="d-menu" data-role="dropdown">
                        <?php if (isset($templates) && count($templates) > 0) foreach ($templates as $template){?>
                            <li><a href="/code?template=<?php echo $template['name']?>"><img class="icon" src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>"><?php echo $template['title']?></a></li>
                        <?php }?>
                    </ul>
                </div>
            </li>

            <li class="d-none-md">
                <a href="" class="dropdown-toggle">New</a>
                <ul class="d-menu" data-role="dropdown">
                    <?php if (isset($templates) && count($templates) > 0) foreach ($templates as $template){?>
                        <li><a href="/code?template=<?php echo $template['name']?>"><img class="icon" src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>"><?php echo $template['title']?></a></li>
                    <?php }?>
                </ul>
            </li>

            <li title="Save code" class="d-none d-block-md no-hover"><a class="p-0" href="#" onclick="Sandbox.saveCode(true)"><button class="button square success"><span class="mif-floppy-disk icon"></span></button></a></li>
            <li class="d-none-md"><a href="#" onclick="Sandbox.saveCode(true)"><span>Save code</span></a></li>

            <li title="Debug code" class="d-none d-block-md no-hover" style="display: <?php echo $code['hash'] == 'new' ? 'none' : 'block'?>"><a class="p-0" target="_blank" id="code_page-debug_button" href="<?php echo $code['hash'] == 'new' ? '#' : '/'.$code['user_name'].'/debug/' . $code['hash'] ?>"><button class="button square warning"><span class="mif-bug icon"></span></button></a></li>
            <li class="d-none-md" style="display: <?php echo $code['hash'] == 'new' ? 'none' : 'block'?>"><a target="_blank" id="code_page-debug_button" href="<?php echo $code['hash'] == 'new' ? '#' : '/'.$code['user_name'].'/debug/' . $code['hash'] ?>"><span>Debug code</span></a></li>

            <li title="Fork code" class="d-none d-block-md no-hover" style="display: <?php echo $code['hash'] == 'new' ? 'none' : 'block'?>"><a class="p-0" id="code_page-fork_button" href="#" onclick="Sandbox.fork('<?php echo $code['hash']?>'); return false;"><button class="button square secondary"><span class="mif-copy icon"></span></button></a></li>
            <li class="d-none-md" style="display: <?php echo $code['hash'] == 'new' ? 'none' : 'block'?>"><a id="code_page-fork_button" href="#" onclick="Sandbox.fork('<?php echo $code['hash']?>'); return false;"><span>Fork code</span></a></li>

            <li title="Code settings" class="d-none d-block-md no-hover"><a class="p-0" href="#" onclick="Metro.dialog.open('#code-settings')"><button class="button square dark"><span class="mif-cogs icon"></span></button></a></li>
            <li class="d-none-md"><a href="#" onclick="Metro.dialog.open('#code-settings')"><span>Code settings</span></a></li>

            <?php if ($_SESSION['current'] != -1) {?>
            <li class="ml-1 d-none d-block-md no-hover">
                <div class="dropdown-button">
                    <button class="button p-0"><img class="h-100" data-role="gravatar" data-default="mm" data-email="<?php echo $_SESSION['user']['email']?>"></button>
                    <ul class="t-menu compact vertical pos-absolute" data-role="dropdown" style="top: 100%;">
                        <li><a href="/"><span class="mif-dashboard"></span></a></li>
                        <li><a href="/profile"><span class="mif-profile"></span></a></li>
                        <li><a href="/cogs"><span class="mif-cogs"></span></a></li>
                    </ul>
                </div>
            </li>

            <li class="d-none-md">
                <a class="dropdown-toggle"><?php echo $_SESSION['user']['name']?></a>
                <ul class="d-menu place-right" data-role="dropdown">
                    <li><a href="/">Dashboard</a></li>
                    <li><a href="/profile">Profile</a></li>
                    <li><a href="/settings">Settings</a></li>
                </ul>
            </li>

            <li class="ml-1 mr-1 d-none d-block-md no-hover"><a class="p-0" href="/logout"><button class="button square"><span class="mif-exit icon"></span></button></a></li>
            <li class="d-none-md"><a href="/logout"></span><span>Logout</span></a></li>

            <?php } else {?>
                <li><a href="/login">Log in</a></li>
            <?php } ?>
        </ul>

    </header>
</div>

<form action="javascript:" id="editor_form" class="h-100">
    <input type="hidden" name="code_id" id="code_id" value="<?php echo $code['id'] ?>">
    <input type="hidden" name="code_hash" id="code_hash" value="<?php echo $code['hash'] ?>">
    <input type="hidden" name="template" id="template" value="<?php echo $code['template_id'] ?>">
    <input type="hidden" name="temp_file" id="temp_file" value="<?php echo $code['temp_file'] ?>">
    <input type="hidden" name="saved" id="saved" value="<?php echo $code['saved'] ?>">
    <input type="hidden" name="alien" id="alien" value="<?php echo $code['alien'] ?>">

    <div data-role="splitter" data-split-sizes="60, 40" class="h-100">
        <div id="browser" data-role="splitter" data-split-sizes="80, 20" data-split-mode="vertical" data-min-sizes="40">
            <div class="iframe-wrapper">
                <div id="iframe_reload" class="pos-absolute pos-top-right z-2" style="width: 100px; display: none">
                    <div data-role="activity" data-type="metro" data-style="color"></div>
                </div>
                <iframe src="<?php echo $code['iframe'] ?>"
                        id="iframe"
                        allowfullscreen
                        allowtransparency
                        sandbox="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts"
                        frameborder="0"
                        class="z-1"
                ></iframe>
            </div>
            <div class="d-flex flex-column console-wrapper">
                <div class="wrapper-header">Console</div>
                <div class="output-wrapper" id="console-output"></div>
                <input type="text" data-role="input" data-cls-component="mt-auto" data-prepend="<span class='mif-chevron-right'>" data-history="true" data-on-enter-click="Sandbox.sendMessageToIframe($('#iframe')[0], this.value)">
            </div>
        </div>
        <div data-role="splitter" data-split-mode="vertical" data-min-sizes="40">
            <div id="html-code">
                <div class="wrapper-header">
                    <span>HTML</span>
                    <div class="ml-auto">
                        <button class="button small square"><span class="mif-chevron-thin-down" onclick="Sandbox.collapseBlock('html')"></span></button>
                        <button class="button small square"><span class="mif-chevron-thin-up" onclick="Sandbox.expandBlock('html')"></span></button>
                    </div>
                </div>
                <div class="code-wrapper">
                    <textarea name="html_editor" id="html_editor" placeholder="HTML code goes here..."><?php echo $code['html'] ?></textarea>
                </div>
            </div>
            <div id="css-code">
                <div class="wrapper-header">
                    <span>CSS</span>
                    <div class="ml-auto">
                        <button class="button small square"><span class="mif-chevron-thin-down" onclick="Sandbox.collapseBlock('css')"></span></button>
                        <button class="button small square"><span class="mif-chevron-thin-up" onclick="Sandbox.expandBlock('css')"></span></button>
                    </div>
                </div>
                <div class="code-wrapper">
                    <textarea name="css_editor" id="css_editor" placeholder="CSS code goes here..."><?php echo $code['css'] ?></textarea>
                </div>
            </div>
            <div id="js-code">
                <div class="wrapper-header">
                    <span>JavaScript</span>
                    <div class="ml-auto">
                        <button class="button small square"><span class="mif-chevron-thin-down" onclick="Sandbox.collapseBlock('js')"></span></button>
                        <button class="button small square"><span class="mif-chevron-thin-up" onclick="Sandbox.expandBlock('js')"></span></button>
                    </div>
                </div>
                <div class="code-wrapper">
                    <textarea name="js_editor" id="js_editor" placeholder="JavaScript code goes here..."><?php echo $code['js'] ?></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

<?php include "foot.phtml"; ?>
