<?php include "head.phtml"?>

<div class="container-fluid bg-darkViolet fg-white pos-fixed fixed-top z-top">
    <header class="app-bar container bg-darkViolet fg-white pos-relative" data-role="appbar" data-expand-point="md">
        <a class="app-bar-item no-hover" href="/"><img src="<?php echo VIEW_PATH?>images/sandbox.svg" style="height: 40px"></a>
        <a class="app-bar-item no-hover" href="/"><span class="enlarge-4">Sandbox Dashboard</span></a>

        <ul class="app-bar-menu ml-auto">
            <li title="User options" class="ml-1 d-none d-block-md no-hover">
                <div class="dropdown-button">
                    <button class="button p-0  bg-transparent"><img class="h-100 va-baseline" data-role="gravatar" data-default="mm" data-email="<?php echo $_SESSION['user']['email']?>"></button>
                    <ul class="t-menu compact vertical pos-absolute bg-darkViolet fg-white shadow-1" data-role="dropdown" style="top: 100%;">
                        <li><a href="/"><span class="mif-dashboard"></span></a></li>
                        <li><a href="/profile"><span class="mif-user"></span></a></li>
                        <li><a href="/cogs"><span class="mif-cogs"></span></a></li>
                    </ul>
                </div>
            </li>

            <li class="d-none-md">
                <a class="dropdown-toggle marker-light"><?php echo $_SESSION['user']['name']?></a>
                <ul class="d-menu place-right" data-role="dropdown">
                    <li><a href="/">Dashboard</a></li>
                    <li><a href="/profile">Profile</a></li>
                    <li><a href="/settings">Settings</a></li>
                </ul>
            </li>

            <li title="Logout" class="ml-1 mr-1 d-none d-block-md no-hover"><a class="pl-1 pr-1" href="/logout"><button class="button square bg-transparent"><span class="mif-exit mif-2x icon fg-white"></span></button></a></li>
            <li class="d-none-md"><a href="/logout"></span><span>Logout</span></a></li>
        </ul>
    </header>
</div>

<div class="hero text-center add-neb" style="padding-top: 40px; padding-bottom: 40px">
    <h1 class="fg-white">Quick templates</h1>
    <div class="d-flex flex-justify-center mt-10">
        <?php if (isset($top_templates) && count($top_templates) > 0) foreach ($top_templates as $template){?>
            <a class="code-template no-decor" href="/code?template=<?php echo $template['name']?>">
                <img src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>">
                <span class="name"><?php echo $template['title']?></span>
            </a>
        <?php }?>
    </div>
    <div class="d-flex flex-justify-center mt-10">
        <?php if (isset($templates) && count($templates) > 0) foreach ($templates as $template){?>
            <a class="template-small no-decor" href="/code?template=<?php echo $template['name']?>" data-role="hint" data-hint-text="<?php echo $template['title']?>">
                <img src="<?php echo VIEW_PATH?>images/<?php echo $template['icon']?>">
            </a>
        <?php }?>
    </div>
</div>

<div class="container-fluid bg-white pt-10 pb-20 about add-neb">
    <div class="container">
        <div class="d-flex flex-justify-between flex-align-center">
            <p class="text-medium">Recent codes</p>
            <div class="ml-auto">
                <span class="text-muted text-small">Sort by: </span><span class="mr-2 text-bold reduce-1" id="sort-by">Name <span class='mif-arrow-up'></span></span>
                <div class="dropdown-button">
                    <button class="button dropdown-toggle"><span class="mif-import-export mif-2x"></span></button>
                    <ul class="d-menu place-right context" data-role="dropdown">
                        <li><a class="pl-4" href="#" onclick="Sandbox.sortList('.code-items', 'name')">By name</a></li>
                        <li><a class="pl-4" href="#" onclick="Sandbox.sortList('.code-items', 'created')">By created</a></li>
                        <li><a class="pl-4" href="#" onclick="Sandbox.sortList('.code-items', 'updated')">By updated</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <ul class="code-items" data-role="list"
            data-sort-class="name"
            data-sort-dir="asc"
            data-items="20"
            data-show-pagination="true"
            data-show-search="true"
            data-show-list-info="true"
            data-cls-component="mt-4"
            data-cls-list-info="mt-2 mb-2"
            data-filter-class="name"
            data-list-search-title="Search by name:"
            id="code-items">
            <?php if (isset($codes) && $codes != false) foreach ($codes as $code) {?>
                <li class="code-item" data-hash="<?php echo $code['hash']?>">
                    <div class="d-none"><?php echo $code['hash']?></div>
                    <div class="icon"><img src="<?php echo VIEW_PATH?>images/<?php echo $code['template_icon']?>"></div>
                    <div class="name"><a href="/<?php echo $code['user_name'] . "/code/" . $code['hash']?>"><?php echo $code['title']?></a></div>

                    <div class="d-none updated"><?php echo strtotime($code['updated'])?></div>
                    <div class="d-none created"><?php echo strtotime($code['created'])?></div>

                    <div class="date d-none d-block-md" style="padding-top: 14px">
                        <div style="font-size: 9px">
                            <div class="place-right" style="right: 29px;"><?php echo date("H:i:s", strtotime($code['updated']))?></div>
                            <span class="fg-cyan">updated</span>
                        </div>
                        <?php echo date("d-m-Y", strtotime($code['updated']))?>
                    </div>
                    <div class="date d-none d-block-md" style="padding-top: 14px">
                        <div style="font-size: 9px">
                            <div class="place-right" style="right: 29px;"><?php echo date("H:i:s", strtotime($code['created']))?></div>
                            <span class="fg-teal">created</span>
                        </div>
                        <?php echo date("d-m-Y", strtotime($code['created']))?>
                    </div>
                    <div class="buttons d-flex flex-align-center flex-justify-end" style="width: 100px;">
                        <button title="Fork" class="button square secondary" onclick="Sandbox.fork('<?php echo $code['hash']?>')"><span class="mif-copy"></span></button>
                        <button title="Debug" class="button square warning" onclick="Sandbox.open('<?php echo "/".$code['user_name'] . "/debug/" . $code['hash']?>', '_blank')"><span class="mif-bug"></span></button>
                        <button title="Delete" class="button square alert" onclick="Sandbox.delete('<?php echo $code['hash']?>')"><span class="mif-bin"></span></button>
                    </div>
                </li>
            <?php }?>
        </ul>
    </div>
</div>

<div class="container-fluid bg-white bg-light fg-dark" data-role="htmlcontainer" data-html-source="/Views/thanks.phtml"></div>

<footer class="footer-bg" data-role="htmlcontainer" data-html-source="/Views/footer.phtml"></footer>

<?php include "foot.phtml";?>