<script src="<?php echo VIEW_PATH ?>vendors/jquery/jquery-3.3.1.min.js"></script>
<script src="<?php echo VIEW_PATH ?>vendors/metro/js/metro.js?ver=@@b-version"></script>

<?php if (isset($foot_scripts)) foreach ($foot_scripts as $key=>$val) {?>
<script data-script="<?php echo $key?>" src="<?php echo $val?>"></script>
<?php }?>

<script>
    $("#loading").fadeOut(1000, function(){
        $(this).remove();
    });
</script>

</body>
</html>
