<script src="<?php echo VIEW_PATH ?>vendors/jquery/jquery-3.3.1.min.js"></script>
<script src="<?php echo VIEW_PATH ?>vendors/metro/js/metro.js?ver=@@b-version"></script>

<?php if (isset($foot_scripts)) foreach ($foot_scripts as $key=>$val) {?>
<script data-script="<?php echo $key?>" src="<?php echo $val?>"></script>
<?php }?>

<script>
    window.on_page_functions.forEach(function(f){
        Metro.utils.exec(f);
    });
</script>

</body>
</html>
