<div class="container pt-20 pb-20">
    <div class="text-center">
        <ul class="inline-list reduce-1" id="social-menu">
            <li><a href="https://www.facebook.com/metrouicss/"><span class="mif-facebook"></span></a></li>
            <li><a href="https://twitter.com/MetroUI"><span class="mif-twitter"></span></a></li>
            <li><a href="#"><span class="mif-youtube"></span></a></li>
            <li><a href="https://github.com/olton/Metro-UI-CSS"><span class="mif-github"></span></a></li>
        </ul>
    </div>

    <div class="text-center mt-10">
        <ul class="inline-list reduce-1" id="footer-menu">
            <li><a href="https://github.com/olton/Metro-UI-CSS/blob/master/LICENSE">License</a></li>
            <li><a href="mailto:sergey@pimenov.com.ua">Author</a></li>
            <li><a href="https://forum.metroui.org.ua">Forum</a></li>
            <li><a href="https://github.com/olton/Metro-UI-CSS/issues">Issues</a></li>
            <li><a href="https://github.com/olton/Metro-UI-CSS/releases">Releases</a></li>
        </ul>
    </div>

    <div class="text-center m-10">
        <span class="h2"><span class="fg-cyan">Made in </span><span class="fg-yellow">Ukraine</span></span>
    </div>

    <div class="text-center mt-10 reduce-1">
        <a href="https://metroui.org.ua" target="_blank">Metro 4</a> &copy; 2012-2018 by <a href="mailto:sergey@pimenov.com.ua" class="no-wrap">Sergey Pimenov</a>.
        <br />
        Metro 4 Sandbox &copy; 2018 by <a href="mailto:sergey@pimenov.com.ua" class="no-wrap">Sergey Pimenov</a>.
        <br />
        <span class="no-wrap">Domain by <a href="https://imena.ua/">Imena.ua</a>.</span>
        <span class="no-wrap">Hosting by <a href="https://mirohost.net/">Mirohost</a>.</span>
        <br/>
        <span class="no-wrap">Metro CDN by <a href="https://www.keycdn.com/">KeyCDN</a>.</span>
        <br/>
        <span class="no-wrap">IDE PhpStorm by <a href="https://www.jetbrains.com/">JetBrains</a>.</span>
        <br />
        Currently <span class="version-number-full">2018.1-alpha</span>. Code licensed <a href="https://github.com/olton/Metro4-Sandbox/blob/master/LICENSE">MIT</a>.
    </div>
</div>
