<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<!--    <meta name="metro4:init" content="false">-->

    <meta name="twitter:site" content="@pimenov_sergey">
    <meta name="twitter:creator" content="@pimenov_sergey">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="The Sandbox">
    <meta name="twitter:url" content="https://sandbox.org.ua">
    <meta name="twitter:description" content="The Sandbox is a tool for prototyping and testing your HTML, CSS and JavaScript code and getting support with your problems. You write code in the browser and see the results of it as you build.">
    <meta name="twitter:image" content="https://sandbox.org.ua/android-chrome-512x512.png">

    <meta property="og:url" content="https://sandbox.org.ua">
    <meta property="og:title" content="The Sandbox">
    <meta property="og:description" content="The Sandbox is a tool for prototyping and testing your HTML, CSS and JavaScript code and getting support with your problems. You write code in the browser and see the results of it as you build.">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://sandbox.org.ua/android-chrome-512x512.png">
    <meta property="og:image:secure_url" content="https://sandbox.org.ua/android-chrome-512x512.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="512">
    <meta property="og:image:height" content="512">

    <meta name="author" content="Sergey Pimenov">
    <meta name="description" content="The Sandbox is a tool for prototyping and testing your HTML, CSS and JavaScript code and getting support with your problems. You write code in the browser and see the results of it as you build.">
    <meta name="keywords" content="HTML, CSS, JS, Metro, CSS3, Javascript, HTML5, UI, Library, Web, Development, Framework">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#603cba">
    <meta name="theme-color" content="#ffffff">

    <link href="<?php echo VIEW_PATH ?>vendors/metro/css/metro-all.css?ver=@@b-version" rel="stylesheet">
    <link href="<?php echo VIEW_PATH ?>css/sandbox.css" rel="stylesheet">

    <?php if (isset($head_styles)) foreach ($head_styles as $key=>$val) {?>
        <link data-script="<?php echo $key?>" href="<?php echo $val?>" rel="stylesheet">
    <?php }?>

    <?php if (isset($head_scripts)) foreach ($head_scripts as $key=>$val) {?>
        <script data-script="<?php echo $key?>" src="<?php echo $val?>"></script>
    <?php }?>

    <script>
        window['on_page_functions'] = [];
    </script>

    <title><?php echo $page_title ?></title>
</head>
<body class="m4-cloak <?php echo isset($body_class) ? $body_class : "" ?>">
