<?php include "head.phtml"?>

<div class="container-fluid bg-darkViolet fg-white pos-fixed fixed-top z-top">
    <header class="app-bar container bg-darkViolet fg-white pos-relative" data-role="appbar" data-expand-point="md">
        <a class="app-bar-item no-hover" href="/"><img src="<?php echo VIEW_PATH?>images/sandbox.svg" style="height: 40px"></a>
        <a class="app-bar-item no-hover" href="/"><span class="enlarge-4">The Sandbox</span></a>
        <ul class="app-bar-menu ml-auto">
            <li class="d-none">
                <a href="#" class="dropdown-toggle marker-light"><span class="mif-plus"></span></a>
                <ul data-role="dropdown" class="d-menu">
                    <li><a href="/code?template=default"><img class="icon" src="<?php echo VIEW_PATH ?>images/ms.svg">Metro 4</a></li>
                    <li><a href="/code?template=metro4_vue"><img class="icon" src="<?php echo VIEW_PATH ?>images/m4-vue.png">Metro 4 + VueJS</a></li>
                    <li><a href="/code?template=vue"><img class="icon" src="<?php echo VIEW_PATH ?>images/vue.svg">VueJS</a></li>
                    <li><a href="/code?template=html"><img class="icon" src="<?php echo VIEW_PATH ?>images/html.png">HTML</a></li>
                </ul>
            </li>
            <li><a href="/signup">Sign up</a></li>
        </ul>
    </header>
</div>

<div class="hero add-neb fg-white pt-20 pb-20 pl-0 pr-0">
    <div class="container2">
        <div class="row">
            <div class="cell-md-12">
                <div class="login-header">
                    <h1 class="pl-2"><span class="enlarge-5">Log in</span><small class="no-wrap fg-gray"> or <a class="fg-yellow" href="/signup">Sign up now!</a></small></h1>
                    <div data-role="activity" data-type="metro" id="activity" style="visibility: hidden"></div>
                </div>

                <hr class="mt-6 thin bg-transparent">

                <div class="login-box row ml-0 mr-0 mt-4 flex-column flex-row-md">
                    <div class="cell-md-6">
                        <form>
                            <div class="form-group">
                                <label>USERNAME OR EMAIL</label>
                                <input class="input-large" type="text" data-role="input" name="name">
                            </div>

                            <div class="form-group">
                                <label>PASSWORD</label>
                                <input class="input-large" type="password" data-role="input" name="password">
                            </div>
                            <div class="form-actions mt-8">
                                <button type="button" onclick="Sandbox.login(this.form)" class="button success large pl-8 pr-8">Log in</button>
                                <button type="button" class="button link fg-lightTeal">Forgot password?</button>
                            </div>
                        </form>
                    </div>

                    <div class="cell-md-2 login-box-divider">
                        <div class="bar top"></div>
                        <div class="or">OR</div>
                        <div class="bar bottom"></div>
                    </div>

                    <div class="cell-md-4 pl-0 pr-0 pb-0 pt-5">
                        <div id="oauth-buttons">
                            <button class="shortcut bg-gitlab fg-white m-1" onclick="Sandbox.go('/oauth/gitlab/login')">
                                <span class="caption">GitLab</span>
                                <span class="mif-gitlab icon"></span>
                            </button>
                            <button class="shortcut bg-lightGreen fg-white m-1 d-none d-inline-block-md">
                            </button>
                            <button class="shortcut bg-twitter fg-white m-1 d-none d-inline-block-md">
                            </button>
                            <button class="shortcut bg-yellow fg-dark m-1" onclick="Sandbox.go('/oauth/github/login')">
                                <span class="caption">GitHub</span>
                                <span class="mif-github icon"></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid bg-white pt-10 pb-20 about add-neb">
    <div class="container text-center">
        <div class="h2 m-10"><span class="reduce-1 enlarge-1-md">What is it?</span></div>
        <div class="text-leader">
            <p class="reduce-1 enlarge-1-md pl-5-fs pr-5-fs pl-20-md pr-20-md">
                The Sandbox is a tool for prototyping and testing your HTML, CSS and JavaScript code and getting support with your problems.
                You write code in the browser and see the results of it as you build.
            </p>
        </div>
    </div>
</div>


<div class="container-fluid bg-white bg-light fg-dark" data-role="htmlcontainer" data-html-source="/Views/thanks.phtml"></div>

<footer class="footer-bg" data-role="htmlcontainer" data-html-source="/Views/footer.phtml"></footer>

<?php include "foot.phtml";?>