<?php include "head.phtml"?>

<div class="container-fluid bg-darkViolet fg-white pos-fixed fixed-top z-top">
    <header class="app-bar container bg-darkViolet fg-white pos-relative" data-role="appbar" data-expand-point="md">
        <a class="app-bar-item no-hover" href="/"><img src="<?php echo VIEW_PATH?>images/sandbox.svg" style="height: 40px"></a>
        <a class="app-bar-item no-hover" href="/"><span class="enlarge-4">Metro 4 Sandbox</span></a>
        <ul class="app-bar-menu ml-auto">
            <li class="d-none">
                <a href="#" class="dropdown-toggle marker-light"><span class="mif-plus"></span></a>
                <ul data-role="dropdown" class="d-menu">
                    <li><a href="/code?template=metro4"><img class="icon" src="<?php echo VIEW_PATH ?>images/ms.svg">Metro 4</a></li>
                    <li><a href="/code?template=metro4_vue"><img class="icon" src="<?php echo VIEW_PATH ?>images/m4-vue.png">Metro 4 + VueJS</a></li>
                    <li><a href="/code?template=vue"><img class="icon" src="<?php echo VIEW_PATH ?>images/vue.svg">VueJS</a></li>
                    <li><a href="/code?template=html"><img class="icon" src="<?php echo VIEW_PATH ?>images/html.png">HTML</a></li>
                </ul>
            </li>
            <?php if ($_SESSION['current'] == -1) {?>
            <li><a href="/login">Log in</a></li>
            <li><a href="/signup">Sign up</a></li>
            <?php } else {?>
            <li><a href="/logout">Logout</a></li>
            <?php } ?>
        </ul>
    </header>
</div>

<div class="hero text-center add-neb">
    <img src="<?php echo VIEW_PATH ?>images/sandbox.svg" style="width: 160px">
    <p class="h1 fg-white"><span class="reduce-1 enlarge-1-md">Metro 4 Sandbox</span><small class="fg-yellow"> alpha</small></p>
    <p class="text-leader2 fg-light text-light mt-4"><span class="reduce-1 enlarge-1-md">Create your <strong>code</strong> in the sandbox<br>and get help from the author and community</span></p>
</div>

<div class="container-fluid bg-white pt-10 pb-20 about add-neb">
    <div class="container text-center">
        <div class="h2 m-10"><span class="reduce-1 enlarge-1-md">What is it?</span></div>
        <div class="text-leader">
            <p class="reduce-1 enlarge-1-md pl-5-fs pr-5-fs pl-20-md pr-20-md">
                Metro 4 Sandbox is a tool for prototyping, testing code and getting support with your problems.
                You write code in the browser and see the results of it as you build.
                The sandbox is intended for testing code created using the <a href="https://metroui.org.ua" class="fg-cyan no-decor">Metro 4</a> components library.
            </p>
        </div>

        <div class="row mt-10">
            <div class="cell-md-4">
                <div class="info-panel rounded no-overflow shadow-3 h-100">
                    <div class="info-panel-header bg-green fg-white">Free for ALL</div>
                    <div class="info-panel-content">
                        <div class="mx-10 my-6"><span class="mif-security mif-8x fg-green"></span></div>
                        <span class="text-leader2">All code, created in Metro 4 Sandbox free, open source and have MIT license</span>
                    </div>
                </div>
            </div>
            <div class="cell-md-4">
                <div class="info-panel rounded no-overflow shadow-3 h-100">
                    <div class="info-panel-header bg-steel fg-white">Easy to use</div>
                    <div class="info-panel-content">
                        <div class="mx-10 my-6"><span class="mif-checkmark mif-8x fg-steel"></span></div>
                        <span class="text-leader2">You do not need to worry about the correct connection of the necessary files, the sandbox will do it itself.</span>
                    </div>
                </div>
            </div>
            <div class="cell-md-4">
                <div class="info-panel rounded no-overflow shadow-3 h-100">
                    <div class="info-panel-header bg-orange fg-white">Special templates</div>
                    <div class="info-panel-content">
                        <div class="mx-10 my-6"><span class="mif-insert-template mif-8x fg-orange"></span></div>
                        <span class="text-leader2">Include special templates for popular frameworks such as VueJS, Angular, etc</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid bg-white bg-light fg-dark" data-role="htmlcontainer" data-html-source="/Views/thanks.phtml"></div>

<footer class="footer-bg" data-role="htmlcontainer" data-html-source="/Views/footer.phtml"></footer>

<?php include "foot.phtml";?>