<div data-role="splitter" data-split-sizes="50, 50" class="h-100" id="splitter-browser" data-save-state="true" data-split-mode="vertical">

    <div data-role="splitter" data-min-sizes="200" id="splitter-code" data-save-state="true">
        <div id="html-code">
            <div class="wrapper-header">
                <button type="button" class="button small square settings-button" onclick="Sandbox.openSettingsTab(1, this)"><span class="mif-cog"></span></button>
                <span>HTML</span>
                <div class="ml-auto">
                    <button class="button small square"><span class="mif-chevron-thin-down" onclick="Sandbox.collapseBlock('html')"></span></button>
                    <button class="button small square"><span class="mif-chevron-thin-up" onclick="Sandbox.expandBlock('html')"></span></button>
                </div>
            </div>
            <div class="code-wrapper">
                <textarea name="html_editor" id="html_editor" placeholder="HTML code goes here..."><?php echo $code['html'] ?></textarea>
            </div>
        </div>
        <div id="css-code">
            <div class="wrapper-header">
                <button type="button" class="button small square settings-button" onclick="Sandbox.openSettingsTab(2, this)"><span class="mif-cog"></span></button>
                <span>CSS</span>
                <div class="ml-auto">
                    <button class="button small square"><span class="mif-chevron-thin-down" onclick="Sandbox.collapseBlock('css')"></span></button>
                    <button class="button small square"><span class="mif-chevron-thin-up" onclick="Sandbox.expandBlock('css')"></span></button>
                </div>
            </div>
            <div class="code-wrapper">
                <textarea name="css_editor" id="css_editor" placeholder="CSS code goes here..."><?php echo $code['css'] ?></textarea>
            </div>
        </div>
        <div id="js-code">
            <div class="wrapper-header">
                <button type="button" class="button small square settings-button" onclick="Sandbox.openSettingsTab(3, this)"><span class="mif-cog"></span></button>
                <span>JavaScript</span>
                <div class="ml-auto">
                    <button class="button small square"><span class="mif-chevron-thin-down" onclick="Sandbox.collapseBlock('js')"></span></button>
                    <button class="button small square"><span class="mif-chevron-thin-up" onclick="Sandbox.expandBlock('js')"></span></button>
                </div>
            </div>
            <div class="code-wrapper">
                <textarea name="js_editor" id="js_editor" placeholder="JavaScript code goes here..."><?php echo $code['js'] ?></textarea>
            </div>
        </div>
    </div>

    <div id="browser" data-role="splitter" data-split-sizes="70, 30" data-min-sizes="40">
        <div class="iframe-wrapper">
            <div id="iframe_reload" class="pos-absolute pos-top-right z-2" style="width: 100px; display: none">
                <div data-role="activity" data-type="metro" data-style="color"></div>
            </div>
            <iframe src="<?php echo $code['iframe'];?>"
                    id="iframe"
                    allowfullscreen
                    allowtransparency
                    sandbox="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts"
                    frameborder="0"
                    class="z-1"
            ></iframe>
            <script>
                window.on_page_functions.push(function(){
                    var iframe = document.getElementById("iframe");
                    if ($(iframe.contentWindow.document).text().contains("Empty, need reload")) Sandbox.saveCode(false);
                });
            </script>
        </div>
        <div class="d-flex flex-column console-wrapper">
            <div class="wrapper-header">
                <button type="button" class="button small square settings-button" onclick="console_clear()"><span class="mif-cross"></span></button>
                <span>Console</span>
            </div>
            <div class="output-wrapper" id="console-output"></div>
            <input type="text" data-role="input"
                   data-prevent-submit="true"
                   data-cls-component="mt-auto"
                   data-prepend="<span class='mif-chevron-right'>"
                   data-history="true"
                   data-on-enter-click="Sandbox.sendMessageToIframe($('#iframe')[0], this.value)">
        </div>
    </div>
</div>
