<script>
    function refreshEditorsForMobile(){
        try {
            Editors.refreshAll();
        } catch (e) {}
    }
</script>

<div>
    <div id="iframe_reload" class="iframe_reload pos-absolute pos-top-right z-2" style="width: 100px; display: none">
        <div data-role="activity" data-type="metro" data-style="color"></div>
    </div>

    <ul data-role="tabs" class="flex-justify-center" data-tabs-type="group" data-expand="true" data-cls-tabs="d-none-lg" data-on-tab="refreshEditorsForMobile">
        <li><a href="#browser">RESULT</a></li>
        <li><a href="#html-code">HTML</a></li>
        <li><a href="#css-code">CSS</a></li>
        <li><a href="#js-code">JS</a></li>
    </ul>
</div>

<div id="browser" data-role="splitter" data-split-sizes="70, 30" data-split-mode="vertical" data-min-sizes="40">
    <div class="iframe-wrapper">
        <iframe src=""
                id="iframe_mobile"
                allowfullscreen
                allowtransparency
                sandbox="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts"
                frameborder="0"
                class="z-1"
        ></iframe>
        <script>
            window.on_page_functions.push(function(){
                var iframe = document.getElementById("iframe_mobile");
                if (Metro.utils.mediaExist("lg")) {
                    iframe.src="";
                    return ;
                }
                iframe.src = "<?php echo $code['iframe'];?>";
                if ($(iframe.contentWindow.document).text().contains("Empty, need reload")) Sandbox.saveCode(false);
            });
        </script>
    </div>
    <div class="d-flex flex-column console-wrapper">
        <div class="wrapper-header">
            <button type="button" class="button small square settings-button" onclick="console_clear()"><span class="mif-cross"></span></button>
            <span>Console</span>
        </div>
        <div class="output-wrapper" id="console-output-mobile"></div>
        <input type="text" data-role="input"
               data-prevent-submit="true"
               data-cls-component="mt-auto"
               data-prepend="<span class='mif-chevron-right'>"
               data-history="true"
               data-on-enter-click="Sandbox.sendMessageToIframe($('#iframe')[0], this.value)">
    </div>
</div>
<div id="html-code">
    <div class="wrapper-header">
        <button type="button" class="button small square settings-button" onclick="Sandbox.openSettingsTab(1, this)"><span class="mif-cog"></span></button>
        <span>HTML</span>
    </div>
    <div class="code-wrapper">
        <textarea name="html_editor_mobile" id="html_editor_mobile" placeholder="HTML code goes here..."><?php echo $code['html'] ?></textarea>
    </div>
</div>
<div id="css-code">
    <div class="wrapper-header">
        <button type="button" class="button small square settings-button" onclick="Sandbox.openSettingsTab(2, this)"><span class="mif-cog"></span></button>
        <span>CSS</span>
    </div>
    <div class="code-wrapper">
        <textarea name="css_editor_mobile" id="css_editor_mobile" placeholder="CSS code goes here..."><?php echo $code['css'] ?></textarea>
    </div>
</div>
<div id="js-code">
    <div class="wrapper-header">
        <button type="button" class="button small square settings-button" onclick="Sandbox.openSettingsTab(3, this)"><span class="mif-cog"></span></button>
        <span>JavaScript</span>
    </div>
    <div class="code-wrapper">
        <textarea name="js_editor_mobile" id="js_editor_mobile" placeholder="JavaScript code goes here..."><?php echo $code['js'] ?></textarea>
    </div>
</div>
