<?php include "head.phtml"?>

<div class="container-fluid bg-darkViolet fg-white pos-fixed fixed-top z-top">
    <header class="app-bar container bg-darkViolet fg-white pos-relative" data-role="appbar" data-expand-point="md">
        <a class="app-bar-item no-hover" href="/"><img src="<?php echo VIEW_PATH?>images/sandbox.svg" style="height: 40px"></a>
        <a class="app-bar-item no-hover" href="/"><span class="enlarge-4">User Profile</span></a>

        <ul class="app-bar-menu ml-auto">
            <li title="User options" class="ml-1 d-none d-block-md no-hover">
                <div class="dropdown-button">
                    <button class="button p-0  bg-transparent"><img class="h-100 va-baseline" data-role="gravatar" data-default="mm" data-email="<?php echo $_SESSION['user']['email']?>"></button>
                    <ul class="t-menu compact vertical pos-absolute bg-darkViolet fg-white shadow-1" data-role="dropdown" style="top: 100%;">
                        <li><a href="/"><span class="mif-dashboard"></span></a></li>
                        <li><a href="/profile"><span class="mif-cogs"></span></a></li>
                    </ul>
                </div>
            </li>

            <li class="d-none-md">
                <a class="dropdown-toggle marker-light"><?php echo $_SESSION['user']['name']?></a>
                <ul class="d-menu place-right" data-role="dropdown">
                    <li><a href="/">Dashboard</a></li>
                    <li><a href="/profile">Profile</a></li>
                </ul>
            </li>

            <li title="Logout" class="ml-1 mr-1 d-none d-block-md no-hover"><a class="pl-1 pr-1" href="/logout"><button class="button square bg-transparent"><span class="mif-exit mif-2x icon fg-white"></span></button></a></li>
            <li class="d-none-md"><a href="/logout"></span><span>Logout</span></a></li>
        </ul>
    </header>
</div>

<div class="container-fluid">
    <div class="container mt-10 mb-20">

            <div class="row">
                <div class="cell-md-2"></div>
                <div class="cell-md-8">
                    <ul data-role="tabs" data-expand-point="sm" data-tabs-type="text" style="margin-left: -.5rem">
                        <li><a href="#user_settings">Profile</a></li>
                        <li><a href="#editor_settings">Editor</a></li>
                    </ul>

                    <div class="tabs-content pt-5 border-top bd-default">

                        <div id="user_settings">
                            <form action="javascript:" data-role="validator" data-required-mode="false" data-use-required-class="false" id="user_profile_form">
                                <div class="form-group">
                                    <label>USERNAME</label>
                                    <input type="text" name="name" class="input-large" data-role="input" data-validate="required" value="<?php echo $user['name'] ?>">
                                </div>
                                <div class="form-group">
                                    <label>EMAIL</label>
                                    <input type="text" name="email" class="input-large" data-role="input" data-validate="required"  value="<?php echo $user['email'] ?>">
                                </div>
                                <div class="form-group">
                                    <label>PASSWORD</label>
                                    <div class="row">
                                        <div class="cell-md-6">
                                            <input type="password" name="password" class="input-large" data-role="input" data-validate="minlength=6">
                                        </div>
                                        <div class="cell-md-6 pt-1 pt-0-md">
                                            <input type="password" name="password_2" class="input-large" data-role="input" data-validate="minlength=6">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions mt-6">
                                    <button class="button success large" type="button" onclick="Sandbox.saveProfile(this.form)">Save profile</button>
                                    <a href="/" class="button link">Cancel</a>
                                </div>
                            </form>
                        </div>

                        <div id="editor_settings"></div>
                    </div>
                </div>
                <div class="cell-md-2"></div>
            </div>


    </div>
</div>

<?php include "thanks.phtml"?>
<?php include "footer.phtml"?>
<?php include "foot.phtml"?>