<div class="container pt-10 pb-20">
    <div class="h2 mt-10 text-center"><span class="reduce-1 enlarge-1-md">Supported by</span></div>

    <div class="row special-thanks">
        <div class="cell-md-4">
            <a href="https://olshansky.ua/"><img src="/Views/images/olshansky.svg"></a>
        </div>
        <div class="cell-md-4">
            <a href="https://www.imena.ua/"><img src="/Views/images/imena_logo.png"></a>
        </div>
        <div class="cell-md-4">
            <a href="https://mirohost.net/"><img src="/Views/images/mirohost_logo.svg"></a>
        </div>
    </div>
</div>
